<section>
	<h3>Cadastrar Produto</h3>
	<?php include_once '../App/views/form_index.phtml';?>
<section>
	<br />
	<br />
	<h3>VISUALIZE AQUI SEUS PROCESSOS:</h3>
	<div class="table-responsive">
		<table class="table table-hover table-sm">
			<thead class="thead-dark">
				<tr>
					<th><scope="row">ID</th>
					<th>Nome</th>
					<th>Descrição</th>
					<th>Data</th>
					<th>Local</th>
					<th>Existente</th>
					<th>Editar</th>
					<th>Deletar</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach($this->view->taskList as $taskItem):?>
					<tr>
						<td><?=$taskItem['ID']?></td>
						<td><?=$taskItem['name']?></td>
						<td><?=$taskItem['description']?></td>
						<td><?=$taskItem['due']?></td>
						<td><?=$taskItem['priority']?></td>
						<td><?=$taskItem['finished']?></td>
						<td>
							<a href="/edit/<?=$taskItem['ID']?>" class="btn btn-warning">Editar</a>
						</td>
						<td>
							<a href="/delete/<?=$taskItem['ID']?>" class="btn btn-danger">Deletar</a>
						</td>
					
					</tr>
				<?php endforeach;?>
			</tbody>
		</table>
	</div>
</section>
