<div class="table-responsive">
	<table class="table table-hover table-sm">
		<thead class="thead-dark">
			<tr>
				<th><scope="row">ID</th>
				<th>Nome</th>
				<th>Descrição</th>
				<th>Data</th>
				<th>Local</th>
				<th>Existente</th>
				<th>Editar</th>
				<th>Deletar</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($this->view->taskList as $taskItem):?>
				<tr>
					<td><?=$taskItem['id']?></td>
					<td><?=$taskItem['name']?></td>
					<td><?=$taskItem['description']?></td>
					<td><?=$taskItem['due']?></td>
					<td><?=$taskItem['priority']?></td>
					<td>
						<a href="/finish/<?=$taskItem['id']?>">
							<?=$taskItem['finished']?> 
						</a>
					</td>
					<td>
						<a href="/edit/<?=$taskItem['id']?>" class="btn btn-warning">Editar</a>
					</td>
					<td>
						<a href="/delete/<?=$taskItem['id']?>" 
						class="btn btn-danger" data-confirm="Você tem certeza que deseja apagar o item selecionado?">
						Deletar</a>
					</td>
					
				</tr>
			<?php endforeach;?>
		</tbody>
	</table>
</div>

	